# Generated by Django 3.2.7 on 2022-01-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='totalRevenue',
            field=models.IntegerField(default=0),
        ),
    ]
