# Generated by Django 3.2.7 on 2022-01-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='route',
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(default='', max_length=100)),
                ('expected_time', models.TimeField(null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
    ]
