# Generated by Django 3.2.7 on 2022-01-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_busroute_expected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='expected_time',
            field=models.TimeField(null=True),
        ),
    ]
