# Generated by Django 3.2.7 on 2022-01-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20220110_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='busNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='route',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
