# Generated by Django 3.2.7 on 2022-01-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20220110_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='busNumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='route',
        ),
    ]
