# Generated by Django 3.2.7 on 2022-01-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_totalrevenue'),
        ('payment_gateway', '0004_auto_20220110_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpayment',
            name='busNumber',
        ),
        migrations.AddField(
            model_name='testpayment',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
    ]
