# Generated by Django 3.2.7 on 2022-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0006_testpayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpayment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
